apiVersion: v1
kind: Service
metadata:
  labels:
    app: wine-app-frontend
    
  name: wine-app-frontend-service-clusterip
  namespace: wine-app
spec:
  ports:
    - name: tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wine-app-frontend