apiVersion: v1
kind: Service
metadata:
  labels:
    app: wine-app-backend
  name: wine-app-backend-service-clusterip
  namespace: wine-app
spec:
  ports:
    - name: tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: wine-app-backend