apiVersion: v1
kind: Service
metadata:
  name: mongodb-wine-app-service-clusterip
  namespace: wine-app
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017